### ISSUE TITLE
The game is stuck on loading audio…

### ISSUE THREAD

**Issue by benjamindepena58** [Nv7-GitHub/elemental7#29]
`

**Comment by Nv7-GitHub** [comment]
Do a hard reload (Ctrl+Shift+R)

**Comment by benjamindepena58** [comment]
I can’t because I’m on iPad

**Comment by Nv7-GitHub** [comment]
E7 isn't meant for iPad, can you use a laptop or desktop instead

**Comment by benjamindepena58** [comment]
I found a way to play it, thanks!
